github:
  defaultPrivate: true
  owner: UozumiMimicopy
  repo: pachislot-setting-prediction
project:
  gitignoreTemplate: Node
  licenseTemplate: Apache-2.0
workflows:
  autoLabel: true
  autoReview: true
  autoSync: true
cli:
  language: ja
  theme: default
  verboseErrors: true
